version: "3"

services:
  frontend-app:
    build: ./frontend
    container_name: frontend-app
    environment:
      - API_URL=192.168.100.4:8000
    # restart: unless-stopped
    ports:
      - 3000:3000

  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
    ports:
      - "5434:5432"
    volumes:
      - "data:/var/lib/postgresql/data"

  backend:
    env_file:
      - ./backend/.env
    entrypoint: ./entrypoint.sh
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    # volumes:
    #   - ./backend:/home/application
    depends_on:
      - db

  backend_celery:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    depends_on:
      - db
    command: celery -A dashboard.celery beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    # volumes:
    #   - .:/home/application

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui_container
    env_file:
      - ./backend/.env
    ports:
      - "81:8080"
    volumes:
      - ./backend/doc:/usr/share/nginx/html/doc
    environment:
      API_URL: doc/openapi.yml
      HOST_BASE_URL: "localhost"

  redis:
    image: redis:latest

volumes:
  data:
    external: true
