version: "3"

services:
  frontend-app:
    build:
      context: ./frontend
    container_name: frontend-app
    environment:
      API_URL1: ${API_URL1}
      API_URL: ${API_URL}
      HOST_BASE_URL: ${HOST_BASE_URL}
    ports:
      - 3000:3000

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - "5434:5432"
    volumes:
      - "data:/var/lib/postgresql/data"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    entrypoint: ./entrypoint.sh
    environment:
      DEBUG_MODE: ${DEBUG_MODE}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      OPENSTACK_URL: ${OPENSTACK_URL}
      OPENSTACK_ADMIN_PASSWORD: ${OPENSTACK_ADMIN_PASSWORD}
      OPENSTACK_ADMIN_USERNAME: ${OPENSTACK_ADMIN_USERNAME}
      OPENSTACK_SSL_CERT_FILE: ${OPENSTACK_SSL_CERT_FILE}
      HOST_BASE_URL: ${HOST_BASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_HOST: ${REDIS_HOST}
      BASE_URL: ${BASE_URL}
    depends_on:
      - db

  backend_celery:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery -A dashboard.celery beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - db
    environment:
      DEBUG_MODE: ${DEBUG_MODE}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      OPENSTACK_URL: ${OPENSTACK_URL}
      OPENSTACK_ADMIN_PASSWORD: ${OPENSTACK_ADMIN_PASSWORD}
      OPENSTACK_ADMIN_USERNAME: ${OPENSTACK_ADMIN_USERNAME}
      OPENSTACK_SSL_CERT_FILE: ${OPENSTACK_SSL_CERT_FILE}
      HOST_BASE_URL: ${HOST_BASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_HOST: ${REDIS_HOST}
      BASE_URL: ${BASE_URL}

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui_container
    ports:
      - "81:8080"
    volumes:
      - ./backend/doc:/usr/share/nginx/html/doc
    environment:
      API_URL: ${API_URL}
      HOST_BASE_URL: ${HOST_BASE_URL}

  redis:
    image: redis:latest

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx-container
    ports:
      - "80:80"
    depends_on:
      - frontend-app
      - backend

volumes:
  data:
